language: cpp
compiler:
- g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - g++-5-multilib
    - g++-multilib
    - lib32z1-dev

install:
- export CC=gcc-5; export CXX=g++-5
- git clone https://github.com/alliedmodders/ambuild.git $TRAVIS_BUILD_DIR/../ambuild
  && cd $TRAVIS_BUILD_DIR/../ambuild && python setup.py build && sudo python setup.py
  install
- git clone https://github.com/alliedmodders/metamod-source.git -b 1.10-dev $TRAVIS_BUILD_DIR/../metamod-source
- git clone https://github.com/alliedmodders/hl2sdk.git -b tf2 $TRAVIS_BUILD_DIR/../hl2sdk-tf2
- git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev $TRAVIS_BUILD_DIR/../sourcemod
script:
- export SOURCEMOD_RELEASE=$(cd $TRAVIS_BUILD_DIR/../sourcemod/build/package/addons/sourcemod
  && pwd)
- mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
- python ../configure.py --enable-optimize
- ambuild
before_deploy:
- cd $TRAVIS_BUILD_DIR/build/package
- zip -r steamid-$TRAVIS_TAG-linux.zip *
deploy:
  provider: releases
  api_key:
    secure: "eu5Qu5mD8rPh9leqZKbWjtfnPS+FA7B/GIQSVv47qu0j9zoKTR5nzul5ty2Luqh3Gdvs00CVBvukvikoYezMeqSguIFlLf+h9RIuscSHypvif+7vDij/CIFzk98JTq+LTJsjUH9s4GxISQntbF7i/gtpxFvyWAl5y4UDeCLCXACKIqNZ9hAoEeHPow69arbOQ+N4b70g8b781ZtmgRL4Qrsg+TdVt9IfLNkNPte+2/aEhzt+e0D6KKlIO0Vz20oAVj/Ws0Kx3si+OM4X49tICReViUODgXONTLYnZNK0JEY7Uw3ynOFYLWcycvBqJixgBLPH5KdVxqpsb+idEH9/YWocPf6XCCJDyII7rM1yAbw3g/QpTli2lHjks+8wBi/3OrajbptRhtzJmjpIIZp0UKeTBC2WMwX4fbY3E7w2cAb3crMTwoy9wtQZlAU1ohtIe+2sXd4KZRpDYPsDRJDjJa3OyW4GSR+HggVXHwfmagJ5fJkhnh++EPhdL5cXhP/6NMtMewhPHyKnSs5BRhYvM63XpfLTUi1sSR+TdqnzrilJTadTbEREukG5jpkwHTw44unCWNzeWW7XEKKi4UKAWIvt7X2Wh/9cZ5ZsOCSExnnDqVYXfcsAW20Unsk36zZXSge6WM7pWOBR6NwLg1zbo2ICqxxcr5RFlJHUvtqmluc="
  file: $TRAVIS_BUILD_DIR/build/package/steamid-$TRAVIS_TAG-linux.zip
  skip_cleanup: true
  on:
    repo: fwdcp/sourcemod-steamid
    tags: true
    all_branches: true
