version: appveyor-{build}

install:
- git clone https://github.com/alliedmodders/ambuild.git %APPVEYOR_BUILD_FOLDER%\..\ambuild && cd %APPVEYOR_BUILD_FOLDER%\..\ambuild && python setup.py build && python setup.py install
- git clone https://github.com/alliedmodders/metamod-source.git -b 1.10-dev %APPVEYOR_BUILD_FOLDER%\..\metamod-source
- git clone https://github.com/alliedmodders/hl2sdk.git -b tf2 %APPVEYOR_BUILD_FOLDER%\..\hl2sdk-tf2
- git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev %APPVEYOR_BUILD_FOLDER%\..\sourcemod

build_script:
- mkdir %APPVEYOR_BUILD_FOLDER%\build && cd %APPVEYOR_BUILD_FOLDER%\build
- "\"%VS140COMNTOOLS%VsDevCmd.bat\""
- python ..\configure.py --enable-optimize
- C:\Python27\Scripts\ambuild.bat

after_build:
- cd %APPVEYOR_BUILD_FOLDER%\build\package
- if /i "%APPVEYOR_REPO_TAG%"=="true" (7z a ..\steamid-%APPVEYOR_REPO_TAG_NAME%-windows.zip *) else (7z a ..\steamid-%APPVEYOR_REPO_COMMIT%-windows.zip *)

artifacts:
- path: build\*.zip

deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: SteamID $(appveyor_repo_tag_name)
  description: ""
  auth_token:
    secure: 951xPSsvO3PqZJHyMAlFcK9Xj8uLt61JX+J7clJKdf86lrVVZmokpcvTVDglPaQt
  artifact: /build\\.*\.zip/
  draft: true
  on:
    appveyor_repo_tag: true
